import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { App } from "../main";
const summary = { incident_id: "11111111-1111-1111-1111-111111111111", title: "Gateway timeout", source: "monitor", severity: "high", status: "open", affected_service: "gateway", created_at: "2026-09-16T12:00:00Z", updated_at: "2026-09-16T12:01:00Z" } as const;
const list = { items: [summary], limit: 10, offset: 0, next_offset: 10 };
const detail = { ...summary, description: "Requests exceeded the latency threshold.", affected_service_hint: "gateway" };
function mockApi(responses: Array<{ status?: number; body?: unknown }>) { vi.spyOn(globalThis, "fetch").mockImplementation(async () => { const response = responses.shift() ?? { body: list }; return new Response(JSON.stringify(response.body ?? {}), { status: response.status ?? 200 }); }); }
function login() { fireEvent.change(screen.getByLabelText("Bearer Token"), { target: { value: "test-token" } }); fireEvent.click(screen.getByRole("button", { name: "Connect" })); }
describe("operator console routes", () => {
  beforeEach(() => { sessionStorage.clear(); localStorage.clear(); window.history.pushState({}, "", "/login"); }); afterEach(() => { cleanup(); vi.restoreAllMocks(); });
  it("redirects protected routes to the masked token login", () => { window.history.pushState({}, "", "/incidents"); render(<App/>); expect(screen.getByLabelText("Bearer Token")).toHaveAttribute("type", "password"); });
  it("renders dashboard incidents after an authenticated session", async () => { mockApi([{ body: list }]); render(<App/>); login(); expect(await screen.findByText("Gateway timeout")).toBeVisible(); expect(screen.getByText("Visible incidents: 1")).toBeVisible(); expect(localStorage.length).toBe(0); });
  it("shows loading and empty dashboard states", async () => { let resolve!: (value: Response) => void; vi.spyOn(globalThis, "fetch").mockReturnValue(new Promise<Response>((done) => { resolve = done; })); render(<App/>); login(); expect(screen.getByRole("status")).toHaveTextContent("Loading incident data"); resolve(new Response(JSON.stringify({ ...list, items: [] }), { status: 200 })); expect(await screen.findByText("No incidents are available on this page.")).toBeVisible(); });
  it("clears session and returns to login on 401", async () => { mockApi([{ status: 401 }]); render(<App/>); login(); expect(await screen.findByText("Session expired or invalid")).toBeVisible(); expect(sessionStorage.getItem("incidentpilot.operator-token")).toBeNull(); });
  it("keeps the session and shows insufficient permissions on 403", async () => { mockApi([{ status: 403 }]); render(<App/>); login(); expect(await screen.findByText("Insufficient permissions")).toBeVisible(); expect(sessionStorage.getItem("incidentpilot.operator-token")).toBe("test-token"); });
  it("renders incidents, sends filters, and paginates", async () => { mockApi([{ body: list }, { body: list }, { body: list }, { body: list }, { body: { ...list, offset: 10, next_offset: null } }]); window.history.pushState({}, "", "/incidents"); sessionStorage.setItem("incidentpilot.operator-token", "test-token"); render(<App/>); expect(await screen.findByText("Gateway timeout")).toBeVisible(); fireEvent.change(screen.getByLabelText("Status filter"), { target: { value: "open" } }); await waitFor(() => expect(vi.mocked(globalThis.fetch).mock.calls.length).toBeGreaterThan(1)); fireEvent.change(screen.getByLabelText("Severity filter"), { target: { value: "high" } }); fireEvent.change(screen.getByLabelText("Affected service filter"), { target: { value: "gateway" } }); await waitFor(() => expect(vi.mocked(globalThis.fetch).mock.calls.length).toBeGreaterThan(3)); fireEvent.click(screen.getByRole("button", { name: "Next" })); await waitFor(() => expect(screen.getByText("Offset 10")).toBeVisible()); const calls = vi.mocked(globalThis.fetch).mock.calls.map((call) => String(call[0])); expect(calls.some((url) => url.includes("status=open"))).toBe(true); expect(calls.some((url) => url.includes("severity=high"))).toBe(true); expect(calls.some((url) => url.includes("affected_service=gateway"))).toBe(true); fireEvent.click(screen.getByRole("button", { name: "Previous" })); });
  it("shows real detail fields without fabricated sections or execution", async () => { mockApi([{ body: detail }]); window.history.pushState({}, "", `/incidents/${summary.incident_id}`); sessionStorage.setItem("incidentpilot.operator-token", "test-token"); render(<App/>); expect(await screen.findByText("Requests exceeded the latency threshold.")).toBeVisible(); expect(screen.queryByText("Investigation")).not.toBeInTheDocument(); expect(screen.queryByRole("button", { name: /execute/i })).not.toBeInTheDocument(); });
  it("shows a safe not-found detail error", async () => { mockApi([{ status: 404 }]); window.history.pushState({}, "", `/incidents/${summary.incident_id}`); sessionStorage.setItem("incidentpilot.operator-token", "test-token"); render(<App/>); expect(await screen.findByText("The requested incident was not found")).toBeVisible(); });
});


